import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import * as fs from 'fs';
import * as path from 'path';
import { IUploader, UploadOptions, UploadResult, EzImageSettings } from "../types";

export class R2Uploader implements IUploader {
    private client: S3Client;
    private settings: EzImageSettings['r2'];

    constructor(settings: EzImageSettings['r2']) {
        this.settings = settings;
        this.client = new S3Client({
            region: "auto",
            endpoint: `https://${settings.accountId}.r2.cloudflarestorage.com`,
            credentials: {
                accessKeyId: settings.accessKeyId,
                secretAccessKey: settings.secretAccessKey,
            },
        });
    }

    async upload(options: UploadOptions): Promise<UploadResult> {
        const fileContent = fs.readFileSync(options.filePath);
        const extension = path.extname(options.originalName);
        const key = options.originalName; // Key is already generated by path template in extension.ts

        await this.client.send(
            new PutObjectCommand({
                Bucket: this.settings.bucketName,
                Key: key,
                Body: fileContent,
                ContentType: this.getContentType(extension),
            })
        );

        const baseUrl = this.settings.publicUrl.endsWith('/')
            ? this.settings.publicUrl.slice(0, -1)
            : this.settings.publicUrl;

        return {
            url: `${baseUrl}/${key}`,
            key: key
        };
    }

    private getContentType(extension: string): string {
        const mimeTypes: { [key: string]: string } = {
            '.png': 'image/png',
            '.jpg': 'image/jpeg',
            '.jpeg': 'image/jpeg',
            '.gif': 'image/gif',
            '.webp': 'image/webp',
            '.svg': 'image/svg+xml',
        };
        return mimeTypes[extension.toLowerCase()] || 'application/octet-stream';
    }
}
